const resolve = () => {
  try {
    return {};
  } catch (error) {
    return {};
  }
};

resolve();
